metadata:
  name: ocdlifts-ingress
  namespace: ocdlifts
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-http  # ← this line is key

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ocdlifts.mancas.me
      secretName: ocdlifts-tls
  rules:
    - host: ocdlifts.mancas.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ocdlifts
                port:
                  number: 80
